name: adhan
description: Adhan for Dart / Muslim Prayer Times Library. Now retrieving Prayer time in Dart easier than ever.
version: 1.1.3
homepage: https://github.com/iamriajul/adhan-dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  vector_math: ^2.0.8
  extended_math: ^0.0.29+1
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
