name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run test with coverage
        run: pub run test --coverage coverage
      - name: upload reports to codecov
        run: curl -s https://codecov.io/bash | bash -f coverage/lcov.info
        env:
          CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
