name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Run test coverage
      run: pub run test_coverage
    - name: Check Code Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      with:
          path: coverage/lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          token: '${{ secrets.CODECOV_TOKEN }}'
